.\" ted's homebrew stats programs
.TH cgram L "22 Oct 1993"
.SH NAME
cgram \- convert text into character n-grams
.SH SYNOPSIS
.B cgram
[
.B \-o
] 
[
.B \-n window-size
] 
[ 
.IR files ...
]
.SH DESCRIPTION
.IX  cgram  ""  "\fLcgram\fP \(em generate character n-grams"
.IX  "generate character n-grams"
.LP
.B cgram
reads text from specified files or from the standard input if no files
are given or a file called "-" is used and outputs each contiguous
\fIn\fP-character combination as it is found.  This can done either by
using a sliding window, or by skipping \fIn\fP characters at a time to
avoid overlap.
.PP
For example,
.IP
example% cgram -n 3 -o x
.LP
causes cgram to print the file name x three characters at a time.  If
x contains
.IP
.nf
1234
5678
.LP
then the output of cgram would be
.IP
.nf
123
4*5
678
.LP
Note the way that the newline character is printed as a '*' to avoid
confusion.  All non-printing characters are handled this way.
.LP
If the \fI-o\fP option had been omitted above, then the session would
have looked like:
.IP
.nf
example% cgram -n 3 -o x
123
234
34*
4*5
*56
567
678
example%
.LP
Here overlapping trigrams are printed.  Generally, overlapping n-grams
should be used with caution since the counts will not be independent.
This can be handled by using conditional probabilities, but care is
advised.  Also, the output will be several times larger than the size
of the input when using overlapping windows.
.SH OPTIONS
.TP
.B \-n window-size
Use a window size other from the default size of 6.
.TP
.B \-o
Do not output overlapping n-grams.
.TP
.B \-s stride
Use a specified stride.  The \fB\-o\fP option is the same as using
\fB\-s\ 1\fP, using neither \fB\-o\fP nor \fB\-s\fP options is the
same as \fB\-s\ N\fP where N is the window size.  A stride of 2 might
be useful with double byte coding systems, although mixed coding
systems which use single bytes for some characters and double bytes
for others would cause problems.  Some file formats for Unicode as
well as most Asian character set representation sets are mixed double
and single character sets.
.SH "SEE ALSO"
.BR grams (L),
.BR hwcount (L),
.BR compare (L),
.BR words (L),
.BR fwords (L),
.SH NOTES
.LP
The program \fIcgram\fP handles 8 bit characters correctly.
