.\" ted's homebrew stats programs
.TH compare L "22 Oct 1993"
.SH NAME
compare \- compare counts
.SH SYNOPSIS
.B compare
[
.B \-p
] 
.IR "file1 file2"
.SH DESCRIPTION
.IX  compare  ""  "\fLcompare\fP \(em compare counts"
.IX  "compare counts"
.LP
.B compare
reads lines from two specified files or from the standard input if a
file called "-" is used and outputs comparisons of the frequency of
occurence of each string found in either of the two input files.  The
comparison is done using the likelihood ratio test used by \fBchi2\ -l\fP
which is also known as the G-statistic.
.PP
For example, the command
.IP
.B
example% compare x y | sort -n
.LP
compares the counts contained in the files \fIx\fP and \fIy\fP and
sorts the results by significance.  If \fIx\fP
contains 
.IP
.nf
10 word1
5 word2
.LP
and \fIy\fP contains
.IP
.nf
20 word1
6 word3
1 word2
.LP
then the output of the command above would be
.IP
.nf
0.256 < word1
5.846 < word3
6.800 > word2
.LP
Which indicates that the counts for \fIword2\fP differ most
significantly in \fIx\fP and \fIy\fP and that \fIword2\fP occurs more
often in \fIx\fP than in \fIy\fP.
.SH OPTIONS
.TP
.B \-p
Compute and print an estimate of how significant the difference in
frequencies is.
.SH "SEE ALSO"
.BR grams (L),
.BR hwcount (L),
.BR chi2 (L),
.BR words (L),
.BR fwords (L),
.SH NOTES
.LP
The maximum length for a word in a count file is 500 characters.
Input which is longer than this maximum will be silently truncated on
output and any words which are identical in the first 500 characters
will not be distinguished.
.LP
As far as \fIcompare\fP is concerned is, a word can contain anything
except a line-feed or null character.  Thus compare can be used to
compare the rates of occurrence of non-overlapping \fIn\fP-grams.
Overlapping \fIn\fP-grams can also be compared, but the independence
assumptions of the likelihood ratio test will be violated and the
results may not be valid.
